# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e2fd9c89a75a1f24698f1d0b6b2a708799ec341c4b6179e218c977614b50f79d7de6ebf26339114fc1206716dc8739b2c3ffb5d84e7e07a327fe936df54869

test:
  secret_key_base: 68c9404b65e0e6875a47cc7fa8ce73d2aa223b9da643ab565d0b82fdb49809a2062d722235a92454b235596ae71a62412778a86c74328e48bf1ce7ea32978910

staging:
  secret_key_base: 3f979525facdf72f4367b95211455f6fef69eff94b79b63aa372521b764ea5109b01eff629fcb715b223dc8cc5bcb469fd66d1b6ddbf6fa6583f56aa3d13663d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
